### ISSUE TITLE
Text is cut during transition

### ISSUE THREAD

**Issue by evowizz** [cashapp/contour#107]
After running the Sample app without any modifications, and clicking the first card; I've noticed that the text is cut by some margin (I think) during the transition.

See the following video: https://imgur.com/amsY2I8

The avatar is acting normally. It is "cut" by the card only at the very bottom. 

I'm not sure what's causing this bug as I'm not very familiar with Contour yet, but I believe it could be because of the `centerY()` part, on this line: 
https://github.com/cashapp/contour/blob/d58fdfd4be2d8e15a007be3d531db7bbcdbd901a/sample-app/src/main/java/com/squareup/contour/sample/ExpandableBioCard1.kt#L74

**Comment by JakeWharton** [comment]
I believe the current working theory is that the text view contains no padding so the `AutoTransition()` which is used delegates to `ChangeBounds()` which overshoots the height change making the text view smaller than is required to display its text.

The workaround is likely adding significant padding to the text view to push it away from the edges of the card vertically so that when the transitions overshoots the destination height it never gets far enough into the padding to clip the text.

**Comment by saket** [comment]
I'd like to get rid of the entire problem by removing `OvershootInterpolator`

**Comment by saket** [comment]
Closing this with #109.
