### ISSUE TITLE
requestLayout doesn't update spec

### ISSUE THREAD

**Issue by ppetarr** [cashapp/contour#136]
My code is really similar to what the readme shows, essentially it's;

```
 message.layoutBy(
            x = if (viewMode == RECOVERY) centerHorizontallyTo { parent.centerX() } else leftTo { parent.left() },
```

where my setter is
```
fun updateMode(mode: Int) {
    viewMode = mode
    requestLayout()
}
````
I change the local variable and then re-request a layout pass, but calling `requestLayout` doesn't update the layout spec as a result my `message` is always centred horizontally, instead of left-aligned. 

----

I've managed to fix my issue by calling `updateLayoutBy` in my set method, but based on the sample-app this isn't required, I assumed `requestLayout` would just re-configure the layout, would still like to get an official answer.

**Comment by saket** [comment]
Updating `viewMode` doesn't do anything because it only gets evaluated once, when the first `layoutBy` is called. It would have gotten evaluated on every layout pass if you were using it inside an `AxisSolver` lambda, somewhat along these lines:

```kotlin
message.layoutBy(
  x = centerHorizontallyTo { if (viewMode == RECOVERY) parent.centerX() else parent.left() }
)
```

Notice how `viewMode` is present inside an `AxisSolver` lambda, not outside. Contour can call only these lambdas on every layout pass. 

If you can't use conditional logic inside lambdas then using `updateLayoutBy` is also a correct way to update the position of your Views.

**Comment by ppetarr** [comment]
> Updating `viewMode` doesn't do anything because it only gets evaluated once, when the first `layoutBy` is called. It would have gotten evaluated on every layout pass if you were using it inside an `AxisSolver` lambda, somewhat along these lines:
> 
> ```kotlin
> message.layoutBy(
>   x = centerHorizontallyTo { if (viewMode == RECOVERY) parent.centerX() else parent.left() }
> )
> ```
> 
> Notice how `viewMode` is present inside an `AxisSolver` lambda, not outside. Contour can only call these lambdas on every layout pass.
> 
> If you can't use conditional logic inside lambdas then using `updateLayoutBy` is also a correct way to update the position of your Views.

Ah, that makes more sense, don't know how I missed that. Fantastic, thank you!
